### ISSUE TITLE
FreshPageModelResolver fails to Resolve type if "Models" keyword is present on the name space

### ISSUE THREAD

**Issue by guitcastro** [rid00z/FreshMvvm#4] opened 2015-05-26 14:34 UTC
Giving the following example:
```
namespace Foo.Bar.PageModels
{
    public class MyPageViewModel
    {
       ...
    }
}
```

Using ``` var name = type.AssemblyQualifiedName.Replace ("Model", string.Empty); ``` Will lead into the follow type: ``` Foo.Bar.Pages.MyPageView ``` witch does not exist.

**Comment by rid00z** [comment] 2015-05-27 01:41
Hi @guitcastro 

Thanks for the feedback, but from this issue it seems it's functioning correctly based on spec, A QuotePageModel will always look for a QuotePage or a MyPageViewModel will find a MyPageView, it's a requirement that the View be a page. 

So I'm not sure what the issue is here, can you provide a sample app or more details?

Thanks

**Comment by guitcastro** [comment] 2015-05-27 01:50
@rid00z The problem is, if you have the "model" string in namespace (Not the class name), it got replace too, leading to an incorrectly type.

**Comment by OlexaLe** [comment] 2016-01-27 21:54
Hi all. I believe that framework works according to its naming conventions. When we agreed to have `Page` and `PageModel` suffixes for classes we implicitly agreed to put pages into **Foo.Bar.Pages** namespace and page models into **Foo.Bar.PageModels**. I think that to make it more intuitive it might be a good idea to specify this in "Conventions" part in Readme. 
Current scenario not follows this convention - `MyPageView` should be placed in **Foo.Bar.Pages**. Those I propose to close this issue.

**Comment by Sylix** [comment] 2016-02-08 18:51
Hi all.
Sometimes it fails to Resolve type.
It is ok when, MyPageViewModel will find a MyPageView, it removes Model at end of MyPageViewModel "word". MyPageViewModel becomes MyPageView.

I am developing an app to control vehicles in parking lot. Vehicle has a model, like: Honda HR-V, Jeep Renegade, Mitsubishi ASX, Peugeot 2008, etc...

The portuguese word to Model is Modelo.

I have a PageModel: ModeloListPageModel and a Page: ModeloListPage to show a list of models of vehicles.
It resolves to: oListPage. Removes Model from beginning and end of the class name.

I know it is very peculiar case.

I am changing the class names to not have Modelo or Model

Thanks.

**Comment by OlexaLe** [comment] 2016-02-08 19:40
Hi @Sylix. This should be fixed by pull request #38. Please try the latest framework version. Unfortunately those changes are not included in the latest library on nuget yet, so you'll need to compile it by yourself.
Thanks!

**Comment by rid00z** [comment] 2016-02-08 21:31
I will upload a new package to nuget now as 1.0 pre3.

**Comment by rid00z** [comment] 2016-02-08 22:10
I've now uploaded pre3.

**Comment by escamoteur** [comment] 2016-02-16 20:19
I just ran into a very similiar Problem. If my Pages were not in the same namespace as the pagemodels I got this exception:

```
02-16 21:07:30.833 D/Mono    ( 3420): Assembly Ref addref FreshMvvm[0xb7f27960] -> FreshIOC[0xb7f26998]: 2
Error while resolving expression: Object reference not set to an instance of an object.
Unhandled Exception:

System.Exception: BREADy.Pages.MainMenuPage, BREADy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null not found

Error while resolving expression: Object reference not set to an instance of an object.
Error while resolving expression: Object reference not set to an instance of an object.
Error while resolving expression: Object reference not set to an instance of an object.
Error while resolving expression: Object reference not set to an instance of an object.
Error while resolving expression: Object reference not set to an instance of an object.
02-16 21:07:30.833 D/Mono    ( 3420): Assembly Ref addref FreshMvvm[0xb7f27960] -> FreshIOC[0xb7f26998]: 2
Error while resolving expression: Object reference not set to an instance of an object.
Unhandled Exception:

System.Exception: BREADy.Pages.MainMenuPage, BREADy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null not found

Error while resolving expression: Object reference not set to an instance of an object.
Error while resolving expression: Object reference not set to an instance of an object.
Error while resolving expression: Object reference not set to an instance of an object.
Error while resolving expression: Object reference not set to an instance of an object.
Error while resolving expression: Object reference not set to an instance of an object.

```

More specifically, It does works if both are in the same namespace OR if pages are in a sub-name space "Pages" and page models ins "PageModels.

**Comment by Looooooka** [comment] 2016-03-04 01:26
It would be nice if we could somehow add some resolving rules...or just override GetPageTypeName to add our own convencion logic. 
This way it would be easier to switch to freshmvvm without renaming all VIEWS and VIEWMODELS to pages and being forced to keep them in the same namespace(i prefer to have them separated)

**Comment by rid00z** [comment] 2016-03-04 01:36
Hi

Actually should be pretty easy to do.

Did you know fresh does support the view modal naming convention?


On Friday, 4 March 2016, Luka <notifications@github.com> wrote:

> It would be nice if we could somehow add some resolving rules...or just
> override GetPageTypeName to add our own convencion logic.
> This way it would be easier to switch to freshmvvm without renaming all
> VIEWS and VIEWMODELS to pages and being forced to keep them in the same
> namespace(i prefer to have them separated)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rid00z/FreshMvvm/issues/4#issuecomment-192047818>.
>


-- 

*Michael Ridland | Technical Director | Xamarin MVP*

XAM Consulting - Mobile Technology Specialists

www.xam-consulting.com

Blog: www.michaelridland.com

**Comment by Looooooka** [comment] 2016-03-04 01:44
No I just started using it and haven't found a way to do this so I was just in the process of moving the views and viewmodels from mvvmcross to the same namespace so it could find the correct view.

**Comment by rid00z** [comment] 2016-08-24 01:17
@Looooooka FreshMvvm now supports ability to use a custom naming convention, see http://www.michaelridland.com/xamarin/announcing-freshmvvm-2-1-and-2-2/

**Closed by rid00z** 2016-08-24 01:17 UTC
